import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({
    text: "codes by completing the quick 30-second countdown. Sobrang laking tulong po para yung website ay laging in top shape. Thanks! ❤️",
  });

  return (
    <>
      <Head>
        <title>Zild Me - Tagalog Programmer Source Codes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Latest Codes:
          </h1>
          <h1 className="text-3xl font-extrabold tracking-tight text-white sm:text-4xl">
            👊 Tagalog{" "}
            <span className="text-[hsl(280,100%,70%)]">Programmer</span>
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://shrinke.me/tictactoejavabasic"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">
                🎮 Java TictacToe{" "}
                <span className="text-[hsl(280,100%,70%)] underline">
                  Link{" "}
                </span>{" "}
                →
              </h3>
              <div className="text-lg">
                Just the basics - TicTacToe 7 classes.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://shrinke.me/calendarjavabasic
              "
              target="_blank"
            >
              <h3 className="text-2xl font-bold">
                📅 Java Calendar{" "}
                <span className="text-[hsl(280,100%,70%)] underline">
                  Link{" "}
                </span>{" "}
                →
              </h3>
              <div className="text-lg">
                Requested by Tiktok follower - Java Calendar is a handy tool for
                working with dates, times, and performing various operations.
              </div>
            </Link>
          </div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white">
              <span className="text-[hsl(280,100%,70%)]">Hello Unlock </span>
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
